package model

import (
	"strings"
	"testing"
)

func TestBuildBoardReadme(t *testing.T) {
	cols := []*Column{
		{
			Name: "TO DO",
			Path: "/board/TO DO",
			Items: []Item{
				{Name: "write spec", FullPath: "/board/TO DO/write spec.md", Preview: []string{"# Draft the API spec", "with examples"}},
				{Name: "fix bug", FullPath: "/board/TO DO/fix bug.md", Pinned: true},
			},
		},
		{Name: "DONE", Path: "/board/DONE"},   // empty column
		{Name: "TO DO", Path: "/board/TO DO2"}, // duplicate name -> unique anchor
	}

	changes := []string{"abc1234 2026-05-25 add feature", "def5678 2026-05-24 fix typo"}
	out := string(buildBoardReadme("My Board", cols, changes, "/board"))

	want := []string{
		"# My Board",
		"## Latest changes",
		"- abc1234 2026-05-25 add feature",
		"## Contents",
		"- [TO DO](#to-do)",
		"- [DONE](#done)",
		"- [TO DO](#to-do-1)", // duplicate column gets a unique anchor
		"## TO DO",
		"## DONE",
		"_No cards._",                          // empty column body
		"- [write spec](TO%20DO/write%20spec.md)", // url-encoded relative link
		"  _Draft the API spec with examples_",     // collapsed preview, markers stripped
		"- [fix bug](TO%20DO/fix%20bug.md)",
		"<!-- generated by kbrd -->",
	}
	for _, w := range want {
		if !strings.Contains(out, w) {
			t.Errorf("readme missing %q\n---\n%s", w, out)
		}
	}

	// Pinned item should sort before the unpinned one.
	if strings.Index(out, "fix bug") > strings.Index(out, "write spec") {
		t.Errorf("pinned card should appear first\n---\n%s", out)
	}
}

func TestSlugify(t *testing.T) {
	cases := map[string]string{
		"TO DO":        "to-do",
		"In Progress!": "in-progress",
		"a_b c":        "a-b-c",
	}
	for in, want := range cases {
		if got := slugify(in); got != want {
			t.Errorf("slugify(%q) = %q, want %q", in, got, want)
		}
	}
}
