package model

import (
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// buildBoardReadme renders a board overview as markdown: a title, an optional
// "Latest changes" section (recent commit lines), a "Contents" table of
// contents linking to one section per column, and a section per column listing
// its cards as links to the underlying .md files with a short preview. linkBase
// is the directory the README is written to; card links are made relative to it.
func buildBoardReadme(name string, cols []*Column, changes []string, linkBase string) []byte {
	var b strings.Builder

	b.WriteString("# ")
	b.WriteString(strings.TrimSpace(name))
	b.WriteString("\n\n")

	if len(changes) > 0 {
		b.WriteString("## Latest changes\n\n")
		for _, line := range changes {
			b.WriteString("- ")
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Pre-compute unique anchors so the TOC and section headings agree.
	anchors := make([]string, len(cols))
	seen := map[string]int{}
	for i, c := range cols {
		slug := slugify(c.Name)
		if n := seen[slug]; n > 0 {
			seen[slug] = n + 1
			anchors[i] = slug + "-" + strconv.Itoa(n)
		} else {
			seen[slug] = 1
			anchors[i] = slug
		}
	}

	b.WriteString("## Contents\n\n")
	if len(cols) == 0 {
		b.WriteString("_No columns._\n")
	}
	for i, c := range cols {
		b.WriteString("- [")
		b.WriteString(c.Name)
		b.WriteString("](#")
		b.WriteString(anchors[i])
		b.WriteString(")\n")
	}
	b.WriteString("\n")

	for _, c := range cols {
		b.WriteString("## ")
		b.WriteString(c.Name)
		b.WriteString("\n\n")

		items := SortItems(c.Items)
		if len(items) == 0 {
			b.WriteString("_No cards._\n\n")
			continue
		}
		for _, it := range items {
			b.WriteString("- [")
			b.WriteString(it.Name)
			b.WriteString("](")
			b.WriteString(relLink(linkBase, it.FullPath))
			b.WriteString(")\n")
			if preview := previewText(it.Preview); preview != "" {
				// Indent so the preview stays attached to its list item.
				b.WriteString("  _")
				b.WriteString(preview)
				b.WriteString("_\n")
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("<!-- generated by kbrd -->\n")
	return []byte(b.String())
}

// writeBoardReadme regenerates README.md at the git repo root from the board's
// current in-memory columns.
func (b *Board) writeBoardReadme() error {
	name := strings.TrimSpace(b.cfg.BoardName)
	if name == "" {
		name = filepath.Base(b.cfg.Path)
	}
	root := b.gitRepoRoot
	if root == "" {
		root = b.cfg.Path
	}
	content := buildBoardReadme(name, b.columns, recentCommits(root, 5), root)
	return os.WriteFile(filepath.Join(root, "README.md"), content, 0o644)
}

// recentCommits returns up to n recent commit lines ("<short-sha> <date> <subject>")
// for the repo at root. Returns nil if git fails or there are no commits yet.
func recentCommits(root string, n int) []string {
	if root == "" {
		return nil
	}
	out, err := exec.Command("git", "--no-optional-locks", "-C", root,
		"log", "--pretty=format:%h %as %s", "--date=short", "-n", strconv.Itoa(n)).Output()
	if err != nil {
		return nil
	}
	var lines []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			lines = append(lines, line)
		}
	}
	return lines
}

// previewText collapses an item's preview lines into a single trimmed, single-line
// string suitable for inline display (newlines and leading markdown markers removed).
func previewText(lines []string) string {
	var parts []string
	for _, l := range lines {
		l = strings.TrimSpace(strings.TrimLeft(l, "#> -*"))
		if l != "" {
			parts = append(parts, l)
		}
	}
	return strings.Join(parts, " ")
}

// relLink builds a forward-slash, URL-encoded markdown link target for target
// relative to base. Falls back to the URL-encoded absolute path if a relative
// path cannot be computed.
func relLink(base, target string) string {
	rel, err := filepath.Rel(base, target)
	if err != nil {
		rel = target
	}
	parts := strings.Split(filepath.ToSlash(rel), "/")
	for i, p := range parts {
		parts[i] = encodeSegment(p)
	}
	return strings.Join(parts, "/")
}

// encodeSegment percent-encodes the characters in a path segment that would
// break a markdown link, while leaving common safe characters readable.
func encodeSegment(s string) string {
	const hex = "0123456789ABCDEF"
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		if isUnreserved(c) {
			b.WriteByte(c)
			continue
		}
		b.WriteByte('%')
		b.WriteByte(hex[c>>4])
		b.WriteByte(hex[c&0x0f])
	}
	return b.String()
}

func isUnreserved(c byte) bool {
	switch {
	case c >= 'A' && c <= 'Z', c >= 'a' && c <= 'z', c >= '0' && c <= '9':
		return true
	case c == '-' || c == '.' || c == '_' || c == '~':
		return true
	}
	return false
}

// slugify mirrors GitHub heading anchors: lowercase, spaces to hyphens, and
// drop anything other than alphanumerics and hyphens.
func slugify(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '-' || r == '_':
			b.WriteByte('-')
		}
	}
	return b.String()
}
