// Package ingest implements the canonical headless card-creation workflow.
// Command, browser, and native UI adapters provide content and typed metadata;
// this package owns destination resolution, frontmatter, durable creation, and
// declarative item_created hooks.
package ingest

import (
	"context"
	"fmt"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"kbrd/board"
	"kbrd/config"
	"kbrd/events"
	"kbrd/frontmatter"
	"kbrd/hook"
)

var sourcePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)

// CaptureMetadata marks a card as captured from an interactive external
// surface. CapturedAt is generated by Service from the same clock as CreatedAt.
type CaptureMetadata struct {
	SourceApp string `json:"source_app,omitempty"`
	URL       string `json:"url,omitempty"`
}

// Request describes one headless card creation. Board and Column are external
// selectors: Board may be a recent-board label or path; Column may be a name,
// a 1-based position, or empty for the first filesystem column.
type Request struct {
	Board   string           `json:"board"`
	Column  string           `json:"column,omitempty"`
	Name    string           `json:"name"`
	Content string           `json:"content"`
	Source  string           `json:"source,omitempty"`
	Capture *CaptureMetadata `json:"capture,omitempty"`
	Safe    bool             `json:"safe,omitempty"`
}

// Warning reports a non-fatal hook loading or execution failure. The card has
// already been created when warnings are returned.
type Warning struct {
	Source  string `json:"source,omitempty"`
	Message string `json:"message"`
}

// Result identifies a successfully created card and any non-fatal warnings.
type Result struct {
	Path     string    `json:"path"`
	Name     string    `json:"name"`
	Board    string    `json:"board"`
	Column   string    `json:"column"`
	Warnings []Warning `json:"warnings,omitempty"`
}

// Service owns injectable process dependencies. Its zero value is ready to
// use; tests may set Now to make metadata deterministic.
type Service struct {
	Now func() time.Time
}

// Create uses a zero-value Service to create one card.
func Create(ctx context.Context, req Request) (Result, error) {
	return Service{}.Create(ctx, req)
}

// Create validates req, enriches its content, writes the card without
// overwriting, and runs declarative creation hooks unless Safe is set.
func (s Service) Create(ctx context.Context, req Request) (Result, error) {
	if strings.TrimSpace(req.Board) == "" {
		return Result{}, fmt.Errorf("board is required")
	}
	if strings.TrimSpace(req.Name) == "" {
		return Result{}, fmt.Errorf("name is required")
	}
	if req.Source != "" && !sourcePattern.MatchString(req.Source) {
		return Result{}, fmt.Errorf("source must contain only letters, digits, dots, underscores, or hyphens")
	}

	ref, err := board.ResolveExisting(req.Board)
	if err != nil {
		return Result{}, err
	}
	cfg, err := config.Load(ref.Path)
	if err != nil {
		return Result{}, err
	}
	columnPath, err := ResolveColumn(ref.Path, req.Column)
	if err != nil {
		return Result{}, err
	}
	name, err := board.SanitizeGeneratedName(req.Name)
	if err != nil {
		return Result{}, fmt.Errorf("sanitize card name: %w", err)
	}

	now := time.Now()
	if s.Now != nil {
		now = s.Now()
	}
	content := addMetadata(req.Content, req, now, cfg.Ingest.CreatedAtFormat)
	path, err := board.CreateItem(columnPath, name, content)
	if err != nil {
		return Result{}, fmt.Errorf("create card in %s: %w", filepath.Base(columnPath), err)
	}

	result := Result{
		Path:   path,
		Name:   name,
		Board:  ref.Label(),
		Column: filepath.Base(columnPath),
	}
	if !req.Safe {
		result.Warnings = runHooks(ctx, cfg, result.Column, name)
	}
	return result, nil
}

func addMetadata(content string, req Request, now time.Time, createdAtLayout string) string {
	utc := now.UTC()
	content = frontmatter.Set(content, "created_at", strconv.Quote(utc.Format(createdAtLayout)))
	if req.Source != "" {
		content = frontmatter.Set(content, "source", strconv.Quote(req.Source))
	}
	if req.Capture != nil {
		content = frontmatter.Set(content, "captured_at", strconv.Quote(utc.Format(time.RFC3339)))
		if req.Capture.SourceApp != "" {
			content = frontmatter.Set(content, "source_app", strconv.Quote(req.Capture.SourceApp))
		}
		if req.Capture.URL != "" {
			content = frontmatter.Set(content, "url", strconv.Quote(req.Capture.URL))
		}
	}
	return content
}

// ResolveColumn resolves an external column selector consistently for every
// ingestion adapter. Numeric selectors are 1-based; empty selects the first
// filesystem column.
func ResolveColumn(boardPath, selector string) (string, error) {
	columns, err := board.Columns(boardPath)
	if err != nil {
		return "", err
	}
	selector = strings.TrimSpace(selector)
	if selector == "" {
		if len(columns) == 0 {
			return "", fmt.Errorf("%w: %s", board.ErrNoColumns, boardPath)
		}
		return filepath.Join(boardPath, columns[0]), nil
	}

	if index, err := strconv.Atoi(selector); err == nil {
		if index < 1 || index > len(columns) {
			return "", fmt.Errorf("column number %d is out of range; board has %d column(s)", index, len(columns))
		}
		return filepath.Join(boardPath, columns[index-1]), nil
	}
	return board.ResolveColumn(boardPath, selector, false)
}

func runHooks(ctx context.Context, cfg config.Config, column, name string) []Warning {
	if !cfg.Hooks.Enabled {
		return nil
	}
	dispatcher, loadWarnings, err := hook.Load(cfg)
	warnings := make([]Warning, 0, len(loadWarnings)+1)
	for _, warning := range loadWarnings {
		warnings = append(warnings, Warning{Source: warning.Source, Message: warning.Message})
	}
	if err != nil {
		return append(warnings, Warning{Source: "hooks", Message: "load hooks: " + err.Error()})
	}
	if dispatcher == nil {
		return warnings
	}

	for _, result := range dispatcher.Dispatch(ctx, events.ItemCreated{Item: events.ItemRef{Column: column, Name: name}}) {
		switch {
		case result.Err != nil:
			warnings = append(warnings, Warning{Source: result.Name, Message: result.Err.Error()})
		case result.ExitCode != 0:
			warnings = append(warnings, Warning{Source: result.Name, Message: fmt.Sprintf("exited %d", result.ExitCode)})
		}
	}
	return warnings
}
